<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceDetail;
use Illuminate\Database\Seeder;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data (using delete instead of truncate to avoid foreign key issues)
        ServiceDetail::query()->delete();
        Service::query()->delete();

        $services = $this->getServicesData();

        foreach ($services as $data) {
            $service = Service::create($data['service']);

            $detailsData = $data['details'];
            $detailsData['service_id'] = $service->id;

            ServiceDetail::create($detailsData);
        }
    }

    private function getServicesData(): array
    {
        return [
            // 1. ESSAY WRITING HELP
            [
                'service' => [
                    'name' => 'Essay Writing Help',
                    'slug' => 'essay-writing',
                    'icon' => '📝',
                    'short_description' => 'Professional essay writing service for all academic levels. Get expertly crafted essays with proper structure, citations, and formatting.',
                    'long_description' => 'Get expert help with your essays from qualified writers holding advanced degrees. We cover all types of essays including argumentative, expository, narrative, descriptive, and analytical. Our writers provide plagiarism-free, well-researched content that meets your specific requirements and academic standards.',
                    'base_price_per_page' => 15.00,
                    'turnaround_min_hours' => 6,
                    'turnaround_max_hours' => 168,
                    'rating' => 4.8,
                    'orders_completed' => 5420,
                    'features' => ['All essay types', 'Any citation style', '100% plagiarism-free', 'Free unlimited revisions', 'Expert writers', 'On-time delivery'],
                    'academic_levels' => ['High School', 'College', 'University', 'Masters', 'PhD'],
                    'subjects' => ['English', 'History', 'Literature', 'Social Sciences', 'Philosophy', 'Psychology', 'Sociology', 'Political Science'],
                    'is_active' => true,
                    'display_order' => 1,
                    'meta_title' => 'Essay Writing Help | Professional Writers from $15/page',
                    'meta_description' => 'Get professional essay writing help from expert writers. 4.8★ rated, plagiarism-free, 24/7 support. All academic levels. Starting at $15/page.',
                ],
                'details' => [
                    'hero_title' => 'Professional Essay Writing Help',
                    'hero_subtitle' => 'Expert writers for all essay types and academic levels',
                    'hero_description' => 'Get high-quality essays written by professional writers with advanced degrees. Plagiarism-free content, timely delivery, and unlimited revisions guaranteed.',
                    'what_we_offer' => [
                        'Argumentative Essays - Present and defend a specific position',
                        'Expository Essays - Explain topics with facts and evidence',
                        'Narrative Essays - Tell compelling stories with clear themes',
                        'Descriptive Essays - Paint vivid pictures with words',
                        'Compare and Contrast Essays - Analyze similarities and differences',
                        'Cause and Effect Essays - Explore relationships between events',
                        'Critical Analysis Essays - Evaluate texts, artworks, or concepts',
                        'Analytical Essays - Break down complex topics systematically',
                        'Persuasive Essays - Convince readers of your viewpoint',
                        'Reflective Essays - Share personal insights and growth',
                    ],
                    'pricing_tiers' => [
                        [
                            'name' => 'Standard',
                            'price' => '$15',
                            'timeframe' => 'per page',
                            'features' => [
                                '7-14 days delivery',
                                'Experienced writer',
                                'Plagiarism report',
                                'Free revisions',
                                'Bibliography included',
                            ],
                        ],
                        [
                            'name' => 'Express',
                            'price' => '$21',
                            'timeframe' => 'per page',
                            'features' => [
                                '3-6 days delivery',
                                'Expert writer',
                                'Priority support',
                                'Plagiarism report',
                                'Free revisions',
                                'Quality guarantee',
                            ],
                        ],
                        [
                            'name' => 'Urgent',
                            'price' => '$30',
                            'timeframe' => 'per page',
                            'features' => [
                                '6-48 hours delivery',
                                'Top-rated writer',
                                'VIP support',
                                'Plagiarism report',
                                'Unlimited revisions',
                                'Money-back guarantee',
                            ],
                        ],
                    ],
                    'process_steps' => [
                        ['title' => 'Submit Details', 'description' => 'Provide your essay requirements, topic, academic level, and deadline through our simple order form.'],
                        ['title' => 'Writer Assignment', 'description' => 'We match you with a qualified writer who specializes in your subject area and academic level.'],
                        ['title' => 'Writing & Review', 'description' => 'Your writer crafts your essay with proper research, citations, and formatting while our QA team reviews it.'],
                        ['title' => 'Delivery & Revisions', 'description' => 'Receive your completed essay before deadline with unlimited free revisions until you are satisfied.'],
                    ],
                    'sample_topics' => [
                        'The Impact of Social Media on Modern Communication',
                        'Climate Change: Causes, Effects, and Solutions',
                        'The Role of Technology in Education',
                        'Shakespeare\'s Influence on Modern Literature',
                        'Mental Health Awareness in Contemporary Society',
                        'The Ethics of Artificial Intelligence',
                    ],
                    'testimonials' => [
                        [
                            'name' => 'Sarah M.',
                            'level' => 'College Junior',
                            'university' => 'UCLA',
                            'rating' => 5,
                            'review' => 'Outstanding essay on social media impact! The writer captured exactly what I needed with strong arguments and perfect citations. Got an A+ on my paper!',
                        ],
                        [
                            'name' => 'James K.',
                            'level' => 'University Student',
                            'university' => 'Boston University',
                            'rating' => 5,
                            'review' => 'Impressed with the quality and quick turnaround. The argumentative essay was well-structured with solid evidence. Highly recommend this service!',
                        ],
                        [
                            'name' => 'Emily R.',
                            'level' => 'High School Senior',
                            'university' => 'Chicago HS',
                            'rating' => 5,
                            'review' => 'My college application essay was perfect! The writer understood my story and helped me present it beautifully. Thank you so much!',
                        ],
                    ],
                    'faqs' => [
                        [
                            'question' => 'What types of essays can you write?',
                            'answer' => 'We write all types of essays including argumentative, expository, narrative, descriptive, compare and contrast, cause and effect, critical analysis, analytical, persuasive, and reflective essays for all academic levels.',
                        ],
                        [
                            'question' => 'How do you ensure essays are plagiarism-free?',
                            'answer' => 'Every essay is written from scratch by our expert writers and checked through advanced plagiarism detection software. We provide a plagiarism report with every order to guarantee 100% original content.',
                        ],
                        [
                            'question' => 'Can I request revisions if needed?',
                            'answer' => 'Yes! We offer unlimited free revisions within 14 days of delivery. If any part of the essay doesn\'t meet your requirements, just let us know and we\'ll revise it until you\'re completely satisfied.',
                        ],
                        [
                            'question' => 'What citation styles do you support?',
                            'answer' => 'We support all major citation styles including APA, MLA, Chicago/Turabian, Harvard, IEEE, and any custom citation style required by your institution.',
                        ],
                        [
                            'question' => 'How quickly can you write my essay?',
                            'answer' => 'We offer flexible deadlines from 6 hours to several weeks. Urgent essays (6-48 hours) are available with our Express and Urgent packages for an additional fee.',
                        ],
                    ],
                    'citation_styles' => ['APA', 'MLA', 'Chicago', 'Harvard', 'Turabian', 'IEEE', 'AMA'],
                    'deliverables' => [
                        'Well-researched essay written from scratch',
                        'Proper thesis statement and clear structure',
                        'Strong arguments supported by credible sources',
                        'Correctly formatted citations and bibliography',
                        'Formatted according to your requirements',
                        'Plagiarism report included',
                        'Unlimited revisions within 14 days',
                    ],
                    'guarantees' => [
                        '100% Plagiarism-free content',
                        'Money-back guarantee if not satisfied',
                        'On-time delivery guaranteed',
                        'Confidentiality protected - your privacy is our priority',
                        'Expert writers with advanced degrees',
                        'Free unlimited revisions',
                    ],
                ],
            ],

            // 2. RESEARCH PAPER HELP
            [
                'service' => [
                    'name' => 'Research Paper Help',
                    'slug' => 'research-paper',
                    'icon' => '🔬',
                    'short_description' => 'Comprehensive research paper writing with thorough literature review, methodology, and data analysis from PhD experts.',
                    'long_description' => 'Expert assistance with research papers across all academic disciplines. Our PhD-qualified writers conduct thorough research using credible scholarly sources, provide proper methodology, accurate citations, and deliver well-structured papers that meet rigorous academic standards.',
                    'base_price_per_page' => 20.00,
                    'turnaround_min_hours' => 24,
                    'turnaround_max_hours' => 336,
                    'rating' => 4.9,
                    'orders_completed' => 3850,
                    'features' => ['Original research', 'Proper methodology', 'Quality scholarly sources', 'Detailed citations', 'PhD experts', 'In-depth analysis'],
                    'academic_levels' => ['College', 'University', 'Masters', 'PhD'],
                    'subjects' => ['Sciences', 'Social Sciences', 'Humanities', 'Business', 'Engineering', 'Medicine', 'Psychology', 'Education'],
                    'is_active' => true,
                    'display_order' => 2,
                    'meta_title' => 'Research Paper Help | Expert Academic Writing Service',
                    'meta_description' => 'Professional research paper help from PhD experts. Original research, proper citations, on-time delivery. Starting at $20/page.',
                ],
                'details' => [
                    'hero_title' => 'Expert Research Paper Writing Service',
                    'hero_subtitle' => 'PhD-qualified researchers for comprehensive academic papers',
                    'hero_description' => 'Get professionally written research papers with thorough literature review, proper methodology, accurate data analysis, and precise citations from experts in your field.',
                    'what_we_offer' => [
                        'Comprehensive Literature Review - Synthesize current research',
                        'Research Methodology Design - Quantitative and qualitative approaches',
                        'Data Collection & Analysis - Statistical and thematic analysis',
                        'Results Interpretation - Clear presentation of findings',
                        'Discussion Section - Connect results to existing research',
                        'Abstract Writing - Concise summary of your paper',
                        'Bibliography Creation - Properly formatted references',
                        'Tables & Figures - Professional data visualization',
                    ],
                    'pricing_tiers' => [
                        [
                            'name' => 'Standard',
                            'price' => '$20',
                            'timeframe' => 'per page',
                            'features' => [
                                '14+ days delivery',
                                'Research specialist',
                                '10+ sources',
                                'Plagiarism report',
                                'Free revisions',
                            ],
                        ],
                        [
                            'name' => 'Premium',
                            'price' => '$28',
                            'timeframe' => 'per page',
                            'features' => [
                                '7-14 days delivery',
                                'PhD researcher',
                                '15+ scholarly sources',
                                'Statistical analysis',
                                'Plagiarism report',
                                'Priority revisions',
                            ],
                        ],
                        [
                            'name' => 'Advanced',
                            'price' => '$40',
                            'timeframe' => 'per page',
                            'features' => [
                                '3-7 days delivery',
                                'Senior PhD expert',
                                '20+ peer-reviewed sources',
                                'Advanced analysis',
                                'Methodology consultation',
                                'Unlimited revisions',
                            ],
                        ],
                    ],
                    'process_steps' => [
                        ['title' => 'Topic Selection', 'description' => 'Define your research question and scope with guidance from our experts if needed.'],
                        ['title' => 'Literature Research', 'description' => 'We conduct comprehensive research using academic databases and peer-reviewed journals.'],
                        ['title' => 'Writing & Analysis', 'description' => 'Your researcher writes with proper methodology and analyzes data using appropriate techniques.'],
                        ['title' => 'Review & Refinement', 'description' => 'Quality assurance team reviews for academic rigor, then deliver with revision support.'],
                    ],
                    'sample_topics' => [
                        'The Effects of Mindfulness Meditation on Stress Reduction',
                        'Renewable Energy Adoption in Developing Countries',
                        'Social Media\'s Impact on Adolescent Mental Health',
                        'Machine Learning Applications in Healthcare',
                        'Gender Inequality in STEM Fields',
                        'Sustainable Business Practices and Profitability',
                    ],
                    'testimonials' => [
                        [
                            'name' => 'Michael P.',
                            'level' => 'PhD Candidate',
                            'university' => 'Stanford University',
                            'rating' => 5,
                            'review' => 'Exceptional research quality! The literature review was comprehensive and the methodology was sound. My advisor was impressed with the depth of analysis.',
                        ],
                        [
                            'name' => 'Jennifer L.',
                            'level' => 'Master\'s Student',
                            'university' => 'Columbia University',
                            'rating' => 5,
                            'review' => 'The statistical analysis was spot-on and the results section was clearly presented. Helped me achieve distinction on my dissertation!',
                        ],
                        [
                            'name' => 'David C.',
                            'level' => 'Undergraduate',
                            'university' => 'UC Berkeley',
                            'rating' => 5,
                            'review' => 'My first major research paper and they made it easy. Well-structured with solid sources and perfect APA formatting. Highly recommend!',
                        ],
                    ],
                    'faqs' => [
                        [
                            'question' => 'What research methods do you use?',
                            'answer' => 'We employ both quantitative and qualitative research methods depending on your requirements. This includes surveys, experiments, case studies, content analysis, statistical analysis, thematic analysis, and mixed methods approaches.',
                        ],
                        [
                            'question' => 'How many sources will be included?',
                            'answer' => 'The number of sources depends on your paper length and academic level. Typically, we include 10-15 sources for undergraduate papers, 15-25 for master\'s level, and 25+ peer-reviewed sources for PhD-level research.',
                        ],
                        [
                            'question' => 'Can you help with data analysis?',
                            'answer' => 'Yes! Our researchers are skilled in various data analysis methods including SPSS, R, Python, Excel for statistical analysis, and NVivo for qualitative data. We provide detailed results interpretation and visualization.',
                        ],
                        [
                            'question' => 'What if I already have some research done?',
                            'answer' => 'No problem! We can work with your existing research, literature review, or data. Just share what you have, and we\'ll build upon it or help refine and complete your paper.',
                        ],
                        [
                            'question' => 'Do you provide research proposals?',
                            'answer' => 'Yes, we can help with research proposals including background, research questions, methodology design, and expected outcomes. This service helps you get approval before conducting your main research.',
                        ],
                    ],
                    'citation_styles' => ['APA', 'MLA', 'Chicago', 'Harvard', 'IEEE', 'AMA', 'Vancouver'],
                    'deliverables' => [
                        'Complete research paper with all sections',
                        'Comprehensive literature review',
                        'Detailed methodology section',
                        'Data analysis with tables and figures',
                        'Properly formatted citations throughout',
                        'Complete reference list/bibliography',
                        'Plagiarism report',
                        'Raw data files (if applicable)',
                    ],
                    'guarantees' => [
                        '100% Original research',
                        'Expert PhD researchers',
                        'Peer-reviewed sources only',
                        'Money-back guarantee',
                        'Free revisions included',
                        'Confidential and secure',
                    ],
                ],
            ],

            // 3. HOMEWORK HELP
            [
                'service' => [
                    'name' => 'Homework Help',
                    'slug' => 'homework-help',
                    'icon' => '📚',
                    'short_description' => 'Quick and reliable homework assistance with step-by-step solutions for all subjects and academic levels.',
                    'long_description' => 'Get fast, accurate help with your homework assignments. Our subject experts provide step-by-step solutions with detailed explanations to help you understand the material and complete assignments correctly.',
                    'base_price_per_page' => 12.00,
                    'turnaround_min_hours' => 3,
                    'turnaround_max_hours' => 48,
                    'rating' => 4.7,
                    'orders_completed' => 8920,
                    'features' => ['Quick turnaround', 'Step-by-step solutions', 'All subjects covered', 'Affordable pricing', 'Expert tutors', 'Clear explanations'],
                    'academic_levels' => ['High School', 'College', 'University'],
                    'subjects' => ['Math', 'Science', 'English', 'Languages', 'Business', 'Social Studies', 'Computer Science', 'Chemistry'],
                    'is_active' => true,
                    'display_order' => 3,
                    'meta_title' => 'Homework Help | 24/7 Online Tutoring from $12',
                    'meta_description' => 'Get instant homework help from experts. All subjects, quick turnaround, step-by-step solutions. Available 24/7.',
                ],
                'details' => [
                    'hero_title' => '24/7 Homework Help Service',
                    'hero_subtitle' => 'Fast, reliable assistance for all subjects',
                    'hero_description' => 'Get your homework done quickly with expert help. Clear explanations, accurate solutions, and affordable prices for students at all levels.',
                    'what_we_offer' => [
                        'Math Problem Solving - Algebra to Calculus',
                        'Science Assignments - Physics, Chemistry, Biology',
                        'Language Exercises - Grammar, writing, literature',
                        'Business Problems - Economics, accounting, finance',
                        'Computer Science Tasks - Programming, algorithms',
                        'Social Studies Questions - History, geography, civics',
                        'Reading Comprehension - Analysis and summaries',
                        'Writing Assignments - Short answers and paragraphs',
                    ],
                    'pricing_tiers' => [
                        [
                            'name' => 'Quick Help',
                            'price' => '$12',
                            'timeframe' => 'per page',
                            'features' => [
                                '24-48 hours',
                                'Expert tutor',
                                'Step-by-step solutions',
                                'Work shown',
                                'Q&A support',
                            ],
                        ],
                        [
                            'name' => 'Same Day',
                            'price' => '$17',
                            'timeframe' => 'per page',
                            'features' => [
                                '12-24 hours',
                                'Priority assignment',
                                'Detailed explanations',
                                'Visual aids included',
                                'Follow-up support',
                            ],
                        ],
                        [
                            'name' => 'Urgent',
                            'price' => '$24',
                            'timeframe' => 'per page',
                            'features' => [
                                '3-12 hours',
                                'Top tutor',
                                'Immediate start',
                                'Extra explanations',
                                'Unlimited questions',
                            ],
                        ],
                    ],
                    'process_steps' => [
                        ['title' => 'Submit Assignment', 'description' => 'Upload your homework questions or problems along with any specific instructions or materials.'],
                        ['title' => 'Expert Review', 'description' => 'A subject expert reviews your homework and begins working on accurate solutions.'],
                        ['title' => 'Solution Delivery', 'description' => 'Receive detailed step-by-step solutions with explanations showing how to solve each problem.'],
                        ['title' => 'Q&A Support', 'description' => 'Ask questions about the solutions to ensure you understand the concepts fully.'],
                    ],
                    'sample_topics' => [
                        'Algebra equations and inequalities',
                        'Chemical reactions and balancing equations',
                        'Literary analysis of classic novels',
                        'World history essay questions',
                        'Physics motion and force problems',
                        'Business case study analyses',
                    ],
                    'testimonials' => [
                        [
                            'name' => 'Alex T.',
                            'level' => 'High School Sophomore',
                            'university' => 'Lincoln HS',
                            'rating' => 5,
                            'review' => 'Saved me so many times! The step-by-step math solutions helped me actually understand how to solve problems, not just get answers.',
                        ],
                        [
                            'name' => 'Lisa W.',
                            'level' => 'College Freshman',
                            'university' => 'NYU',
                            'rating' => 5,
                            'review' => 'Fast and reliable! Got help with chemistry homework at 11 PM and received solutions by morning. The explanations were clear and easy to follow.',
                        ],
                        [
                            'name' => 'Ryan M.',
                            'level' => 'High School Junior',
                            'university' => 'Washington HS',
                            'rating' => 5,
                            'review' => 'Great for catching up when I miss class. The tutors explain everything clearly and answer all my follow-up questions.',
                        ],
                    ],
                    'faqs' => [
                        [
                            'question' => 'What subjects do you cover?',
                            'answer' => 'We cover all major subjects including Math, Science (Biology, Chemistry, Physics), English, Social Studies, Languages, Business, Computer Science, and more. If you have a specific subject, just ask!',
                        ],
                        [
                            'question' => 'How quickly can you help with urgent homework?',
                            'answer' => 'We offer homework help in as little as 3 hours for urgent assignments. Same-day service is available for 12-24 hour deadlines, and our standard service delivers within 48 hours.',
                        ],
                        [
                            'question' => 'Will you just give me answers or help me learn?',
                            'answer' => 'We provide step-by-step solutions with detailed explanations so you can understand the concepts and methods. Our goal is to help you learn, not just complete the assignment.',
                        ],
                        [
                            'question' => 'Can you help with online homework platforms?',
                            'answer' => 'Yes! We can work with most online homework platforms including Pearson MyLab, WebAssign, ALEKS, Blackboard, Canvas, and more. Just provide access or share the questions.',
                        ],
                        [
                            'question' => 'What if I don\'t understand the solution?',
                            'answer' => 'We encourage questions! After receiving your homework solutions, you can ask follow-up questions about any part you don\'t understand and we\'ll provide additional clarification.',
                        ],
                    ],
                    'deliverables' => [
                        'Complete homework solutions',
                        'Step-by-step working for all problems',
                        'Clear explanations of methods used',
                        'Work shown for all calculations',
                        'Graphs, diagrams, or visual aids when needed',
                        'Follow-up Q&A support',
                    ],
                    'guarantees' => [
                        'Accurate solutions',
                        '24/7 availability',
                        'Money-back if incorrect',
                        'On-time delivery',
                        'Subject experts',
                        'Confidential service',
                    ],
                ],
            ],

            // 4. THESIS & DISSERTATION
            [
                'service' => [
                    'name' => 'Thesis & Dissertation Help',
                    'slug' => 'thesis-dissertation',
                    'icon' => '🎓',
                    'short_description' => 'Comprehensive PhD-level thesis and dissertation support from topic selection to defense preparation.',
                    'long_description' => 'Expert assistance with thesis and dissertation writing from PhD researchers. We help with all aspects including topic selection, literature review, methodology design, data collection and analysis, complete chapter writing, and defense preparation.',
                    'base_price_per_page' => 35.00,
                    'turnaround_min_hours' => 168,
                    'turnaround_max_hours' => 720,
                    'rating' => 4.9,
                    'orders_completed' => 1580,
                    'features' => ['PhD experts', 'Complete chapters', 'Statistical analysis', 'Unlimited revisions', 'Defense prep', 'Formatting'],
                    'academic_levels' => ['Masters', 'PhD'],
                    'subjects' => ['All graduate disciplines', 'Business', 'Education', 'Psychology', 'Engineering', 'Medicine', 'Social Sciences'],
                    'is_active' => true,
                    'display_order' => 4,
                    'meta_title' => 'Thesis & Dissertation Help | PhD Experts from $35/page',
                    'meta_description' => 'Professional thesis and dissertation help from PhD experts. Complete chapters, methodology, data analysis. Starting at $35/page.',
                ],
                'details' => [
                    'hero_title' => 'Professional Thesis & Dissertation Support',
                    'hero_subtitle' => 'PhD experts for graduate-level research',
                    'hero_description' => 'Get comprehensive support for your thesis or dissertation from experienced PhD researchers who understand rigorous academic requirements and can guide you to successful completion.',
                    'what_we_offer' => [
                        'Topic Selection & Refinement - Find viable research questions',
                        'Proposal Writing - Get approval from your committee',
                        'Comprehensive Literature Review - Synthesize existing research',
                        'Methodology Design - Quantitative, qualitative, or mixed methods',
                        'Data Collection Strategies - Surveys, interviews, experiments',
                        'Statistical & Thematic Analysis - Expert data interpretation',
                        'Results & Discussion Chapters - Present findings effectively',
                        'Complete Chapter Writing - All chapters from introduction to conclusion',
                        'Defense Preparation - Practice questions and presentation tips',
                        'Formatting & References - University style compliance',
                    ],
                    'pricing_tiers' => [
                        [
                            'name' => 'Chapter Support',
                            'price' => '$35',
                            'timeframe' => 'per page',
                            'features' => [
                                'Individual chapters',
                                'PhD researcher',
                                '30+ sources',
                                'University formatting',
                                '3 rounds of revisions',
                            ],
                        ],
                        [
                            'name' => 'Full Dissertation',
                            'price' => '$32',
                            'timeframe' => 'per page',
                            'features' => [
                                'Complete dissertation',
                                'Senior PhD expert',
                                '50+ scholarly sources',
                                'Advanced analysis',
                                'Unlimited revisions',
                                'Defense preparation',
                            ],
                        ],
                        [
                            'name' => 'Premium Package',
                            'price' => '$45',
                            'timeframe' => 'per page',
                            'features' => [
                                'Full dissertation support',
                                'Subject matter expert',
                                '75+ peer-reviewed sources',
                                'Statistical consultation',
                                'Weekly progress updates',
                                'Comprehensive defense prep',
                            ],
                        ],
                    ],
                    'process_steps' => [
                        ['title' => 'Consultation', 'description' => 'Discuss your research topic, requirements, and timeline with a PhD expert in your field.'],
                        ['title' => 'Proposal & Planning', 'description' => 'Develop your proposal, refine methodology, and create a detailed timeline for completion.'],
                        ['title' => 'Research & Writing', 'description' => 'Conduct research, analyze data, and write chapters with regular progress updates.'],
                        ['title' => 'Review & Defense', 'description' => 'Final revisions based on feedback, formatting check, and preparation for defense.'],
                    ],
                    'sample_topics' => [
                        'Impact of Remote Work on Employee Productivity and Well-being',
                        'Machine Learning Applications in Early Disease Detection',
                        'Educational Technology Integration in K-12 Classrooms',
                        'Climate Change Adaptation Strategies in Coastal Communities',
                        'Consumer Behavior in E-commerce: A Social Psychology Perspective',
                        'Leadership Styles and Organizational Culture in Nonprofits',
                    ],
                    'testimonials' => [
                        [
                            'name' => 'Dr. Patricia H.',
                            'level' => 'PhD Graduate',
                            'university' => 'Harvard University',
                            'rating' => 5,
                            'review' => 'Invaluable support throughout my dissertation journey. The expert helped me refine my methodology and the statistical analysis was exceptional. Successfully defended!',
                        ],
                        [
                            'name' => 'Robert K.',
                            'level' => 'PhD Candidate',
                            'university' => 'MIT',
                            'rating' => 5,
                            'review' => 'Outstanding quality and professionalism. My literature review chapter exceeded my advisor\'s expectations and the data analysis was thorough and accurate.',
                        ],
                        [
                            'name' => 'Maria S.',
                            'level' => 'Master\'s Graduate',
                            'university' => 'Yale University',
                            'rating' => 5,
                            'review' => 'The defense preparation was incredibly helpful. Practiced with tough questions and felt confident going in. Passed with distinction thanks to their support!',
                        ],
                    ],
                    'faqs' => [
                        [
                            'question' => 'Can you help with my entire dissertation or just specific chapters?',
                            'answer' => 'We offer both options! You can get help with individual chapters (like literature review or methodology) or comprehensive support for your entire dissertation from proposal to defense.',
                        ],
                        [
                            'question' => 'How long does it take to complete a dissertation?',
                            'answer' => 'Timeline varies based on length and complexity. Typically, a complete dissertation takes 3-6 months with our support. Individual chapters can be completed in 2-4 weeks. We work with your specific deadline.',
                        ],
                        [
                            'question' => 'Do you provide statistical analysis services?',
                            'answer' => 'Yes! Our PhD researchers are skilled in SPSS, R, Python, SAS, STATA, and other statistical software. We can help with study design, data analysis, results interpretation, and visualization.',
                        ],
                        [
                            'question' => 'Will my dissertation follow my university\'s formatting requirements?',
                            'answer' => 'Absolutely! We format according to your university\'s specific guidelines including margin requirements, heading styles, citation format, table/figure formatting, and any other institutional requirements.',
                        ],
                        [
                            'question' => 'How do you ensure originality in dissertation work?',
                            'answer' => 'All dissertation work is 100% original and custom-written for you. We conduct fresh research, use proper citations, and provide plagiarism reports. Your dissertation will be unique to your research question.',
                        ],
                    ],
                    'citation_styles' => ['APA', 'MLA', 'Chicago', 'Harvard', 'AMA', 'IEEE'],
                    'deliverables' => [
                        'Complete chapters with proper structure',
                        'Comprehensive literature review',
                        'Detailed methodology section',
                        'Data analysis with SPSS/R/Python output',
                        'Tables, figures, and appendices',
                        'Properly formatted references',
                        'Plagiarism report',
                        'Defense presentation slides',
                        'Practice defense questions',
                    ],
                    'guarantees' => [
                        'PhD-level quality',
                        'Original research',
                        'Unlimited revisions until approved',
                        'Confidentiality agreement',
                        'University formatting compliance',
                        'Defense preparation support',
                    ],
                ],
            ],

            // 5. LAB REPORT WRITING
            [
                'service' => [
                    'name' => 'Lab Report Writing',
                    'slug' => 'lab-report',
                    'icon' => '🧪',
                    'short_description' => 'Professional scientific lab report writing with proper methodology, data analysis, and formatting.',
                    'long_description' => 'Expert lab report writing for all science courses. Our science specialists format reports according to scientific standards with proper methodology, accurate data presentation, results analysis, and discussion sections.',
                    'base_price_per_page' => 18.00,
                    'turnaround_min_hours' => 12,
                    'turnaround_max_hours' => 72,
                    'rating' => 4.8,
                    'orders_completed' => 2940,
                    'features' => ['Scientific format', 'Data analysis', 'Graphs & tables', 'Proper citations', 'All sciences', 'Quick turnaround'],
                    'academic_levels' => ['High School', 'College', 'University'],
                    'subjects' => ['Chemistry', 'Physics', 'Biology', 'Biochemistry', 'Engineering', 'Environmental Science'],
                    'is_active' => true,
                    'display_order' => 5,
                    'meta_title' => 'Lab Report Writing Service | Scientific Reports from $18/page',
                    'meta_description' => 'Professional lab report writing for all science courses. Proper format, data analysis, graphs and tables. Starting at $18/page.',
                ],
                'details' => [
                    'hero_title' => 'Professional Lab Report Writing',
                    'hero_subtitle' => 'Expert scientific writing for all disciplines',
                    'hero_description' => 'Get well-structured lab reports with proper scientific format, accurate data presentation, thorough analysis, and clear conclusions from experienced science writers.',
                    'what_we_offer' => [
                        'Title Page & Abstract - Concise experiment summary',
                        'Introduction & Background - Theory and objectives',
                        'Materials & Methods - Detailed procedure',
                        'Results with Data Tables - Organized findings',
                        'Graphs & Charts - Professional visualization',
                        'Discussion & Analysis - Interpret results',
                        'Conclusion - Summarize findings',
                        'References - Properly cited sources',
                        'Appendices - Raw data and calculations',
                    ],
                    'pricing_tiers' => [
                        [
                            'name' => 'Basic',
                            'price' => '$18',
                            'timeframe' => 'per page',
                            'features' => [
                                '48-72 hours',
                                'Science specialist',
                                'Standard format',
                                'Tables included',
                                'Free revisions',
                            ],
                        ],
                        [
                            'name' => 'Advanced',
                            'price' => '$25',
                            'timeframe' => 'per page',
                            'features' => [
                                '24-48 hours',
                                'Expert scientist',
                                'Graphs & charts',
                                'Statistical analysis',
                                'Error analysis',
                                'Multiple revisions',
                            ],
                        ],
                        [
                            'name' => 'Urgent',
                            'price' => '$36',
                            'timeframe' => 'per page',
                            'features' => [
                                '12-24 hours',
                                'PhD scientist',
                                'Professional graphs',
                                'Advanced analysis',
                                'Comprehensive discussion',
                                'Priority support',
                            ],
                        ],
                    ],
                    'process_steps' => [
                        ['title' => 'Share Experiment Details', 'description' => 'Provide your lab manual, experiment data, observations, and any specific requirements from your instructor.'],
                        ['title' => 'Data Analysis', 'description' => 'Our science expert analyzes your data, creates tables/graphs, and performs necessary calculations.'],
                        ['title' => 'Report Writing', 'description' => 'Write complete lab report with proper scientific format, citations, and clear explanations.'],
                        ['title' => 'Quality Review', 'description' => 'Review for accuracy, format compliance, and deliver with revision support.'],
                    ],
                    'sample_topics' => [
                        'Acid-Base Titration Experiment',
                        'Newton\'s Second Law of Motion',
                        'DNA Extraction from Plant Cells',
                        'Measuring Acceleration Due to Gravity',
                        'Enzyme Kinetics and Substrate Concentration',
                        'Electrical Circuit Analysis',
                    ],
                    'testimonials' => [
                        [
                            'name' => 'Brian L.',
                            'level' => 'College Sophomore',
                            'university' => 'Georgia Tech',
                            'rating' => 5,
                            'review' => 'Perfect chemistry lab report! The data tables were well-organized and the discussion section explained everything clearly. Got full marks!',
                        ],
                        [
                            'name' => 'Amanda K.',
                            'level' => 'University Student',
                            'university' => 'UC San Diego',
                            'rating' => 5,
                            'review' => 'Excellent physics lab report with proper error analysis and well-explained calculations. The graphs were professional and clearly labeled.',
                        ],
                        [
                            'name' => 'Chris M.',
                            'level' => 'High School Senior',
                            'university' => 'Roosevelt HS',
                            'rating' => 5,
                            'review' => 'Finally understand how to write a proper lab report! The format was perfect and included everything my teacher required. Thank you!',
                        ],
                    ],
                    'faqs' => [
                        [
                            'question' => 'What scientific disciplines do you cover?',
                            'answer' => 'We cover all major sciences including Chemistry, Physics, Biology, Biochemistry, Microbiology, Engineering, Environmental Science, Anatomy & Physiology, and more.',
                        ],
                        [
                            'question' => 'What if I don\'t have complete data from my experiment?',
                            'answer' => 'Share whatever data and observations you have. Our experts can work with incomplete data and, if necessary, can help identify what additional measurements might be needed or how to address missing data in your report.',
                        ],
                        [
                            'question' => 'Do you create graphs and tables?',
                            'answer' => 'Yes! We create professional graphs, charts, and data tables using Excel or specialized scientific software. All visualizations are properly labeled with titles, axis labels, and legends.',
                        ],
                        [
                            'question' => 'Can you help with error analysis and uncertainty calculations?',
                            'answer' => 'Absolutely! We include proper error analysis, calculate uncertainties, discuss sources of error, and explain how they might have affected your results. This is crucial for a high-quality lab report.',
                        ],
                        [
                            'question' => 'What format do you use for lab reports?',
                            'answer' => 'We follow standard scientific format: Title, Abstract, Introduction, Materials & Methods, Results, Discussion, Conclusion, and References. We also adapt to any specific format required by your instructor.',
                        ],
                    ],
                    'deliverables' => [
                        'Complete lab report (all sections)',
                        'Professionally formatted tables',
                        'High-quality graphs and charts',
                        'Data analysis and calculations',
                        'Error analysis (when applicable)',
                        'Properly formatted references',
                        'Raw data appendix',
                    ],
                    'guarantees' => [
                        'Scientific accuracy',
                        'Proper format and structure',
                        'On-time delivery',
                        'Free revisions',
                        'Expert science writers',
                        'Data confidentiality',
                    ],
                ],
            ],

            // 6. CASE STUDY ANALYSIS
            [
                'service' => [
                    'name' => 'Case Study Analysis',
                    'slug' => 'case-study',
                    'icon' => '💼',
                    'short_description' => 'Professional business case study analysis with SWOT, strategic recommendations, and executive summary.',
                    'long_description' => 'Expert case study analysis for business, management, and healthcare courses. We provide comprehensive problem identification, SWOT analysis, alternative solutions evaluation, and strategic recommendations backed by business theory and research.',
                    'base_price_per_page' => 22.00,
                    'turnaround_min_hours' => 24,
                    'turnaround_max_hours' => 96,
                    'rating' => 4.8,
                    'orders_completed' => 3210,
                    'features' => ['SWOT analysis', 'Strategic recommendations', 'Executive summary', 'Industry research', 'Financial analysis', 'Implementation plan'],
                    'academic_levels' => ['College', 'University', 'Masters', 'MBA'],
                    'subjects' => ['Business', 'Management', 'Marketing', 'Finance', 'Healthcare', 'Strategy', 'Entrepreneurship'],
                    'is_active' => true,
                    'display_order' => 6,
                    'meta_title' => 'Case Study Analysis Help | Business Writing from $22/page',
                    'meta_description' => 'Professional case study analysis with SWOT, recommendations, and executive summary. Business and management expertise. Starting at $22/page.',
                ],
                'details' => [
                    'hero_title' => 'Expert Case Study Analysis',
                    'hero_subtitle' => 'Comprehensive business analysis and strategic recommendations',
                    'hero_description' => 'Get detailed case study analysis with thorough problem identification, SWOT analysis, alternative solutions, and actionable strategic recommendations from business experts.',
                    'what_we_offer' => [
                        'Executive Summary - Concise overview for decision-makers',
                        'Company/Situation Background - Context and history',
                        'Problem Identification - Core issues and challenges',
                        'SWOT Analysis - Strengths, weaknesses, opportunities, threats',
                        'Stakeholder Analysis - Key players and interests',
                        'Alternative Solutions - Multiple strategic options',
                        'Recommendations - Best course of action with justification',
                        'Implementation Plan - Practical steps and timeline',
                        'Financial Analysis - Cost-benefit considerations',
                    ],
                    'pricing_tiers' => [
                        [
                            'name' => 'Standard Analysis',
                            'price' => '$22',
                            'timeframe' => 'per page',
                            'features' => [
                                '72-96 hours',
                                'Business analyst',
                                'SWOT analysis',
                                'Recommendations',
                                '5+ sources',
                                'Free revisions',
                            ],
                        ],
                        [
                            'name' => 'Comprehensive',
                            'price' => '$30',
                            'timeframe' => 'per page',
                            'features' => [
                                '48-72 hours',
                                'Industry expert',
                                'SWOT & PESTEL',
                                'Financial analysis',
                                '10+ sources',
                                'Implementation plan',
                                'Multiple revisions',
                            ],
                        ],
                        [
                            'name' => 'MBA Level',
                            'price' => '$40',
                            'timeframe' => 'per page',
                            'features' => [
                                '24-48 hours',
                                'MBA-qualified analyst',
                                'Multi-framework analysis',
                                'Advanced financial modeling',
                                '15+ sources',
                                'Detailed implementation',
                                'Unlimited revisions',
                            ],
                        ],
                    ],
                    'process_steps' => [
                        ['title' => 'Case Review', 'description' => 'Share the case study details, questions, and any specific frameworks or requirements from your course.'],
                        ['title' => 'Research & Analysis', 'description' => 'Conduct industry research, analyze the situation, and apply relevant business frameworks.'],
                        ['title' => 'Solution Development', 'description' => 'Develop strategic recommendations with justifications based on analysis and business theory.'],
                        ['title' => 'Final Report', 'description' => 'Deliver comprehensive case analysis with executive summary and implementation plan.'],
                    ],
                    'sample_topics' => [
                        'Netflix: Streaming Wars and Global Expansion Strategy',
                        'Tesla\'s Disruption of the Automotive Industry',
                        'Starbucks: Market Entry Strategy in Emerging Markets',
                        'Amazon\'s Supply Chain and Logistics Excellence',
                        'Apple\'s Innovation and Product Development Strategy',
                        'Walmart vs. Amazon: Retail Competition Analysis',
                    ],
                    'testimonials' => [
                        [
                            'name' => 'Thomas B.',
                            'level' => 'MBA Student',
                            'university' => 'Wharton School',
                            'rating' => 5,
                            'review' => 'Excellent strategic analysis! The SWOT was thorough and the recommendations were well-justified with business theory. Professor loved the implementation plan.',
                        ],
                        [
                            'name' => 'Nicole D.',
                            'level' => 'Business Major',
                            'university' => 'USC Marshall',
                            'rating' => 5,
                            'review' => 'Outstanding work on the Netflix case study. The competitive analysis was insightful and the financial projections were realistic. Got an A+!',
                        ],
                        [
                            'name' => 'Kevin P.',
                            'level' => 'MBA Candidate',
                            'university' => 'NYU Stern',
                            'rating' => 5,
                            'review' => 'Professional quality analysis. The expert clearly understood the industry dynamics and provided practical, actionable recommendations.',
                        ],
                    ],
                    'faqs' => [
                        [
                            'question' => 'What business frameworks do you use?',
                            'answer' => 'We use various frameworks including SWOT, PESTEL, Porter\'s Five Forces, Value Chain Analysis, BCG Matrix, Ansoff Matrix, and others depending on your case requirements and course specifications.',
                        ],
                        [
                            'question' => 'Can you handle cases from specific industries?',
                            'answer' => 'Yes! We have experts across various industries including technology, retail, healthcare, finance, manufacturing, hospitality, and more. We can handle industry-specific cases with relevant expertise.',
                        ],
                        [
                            'question' => 'Do you provide financial analysis?',
                            'answer' => 'Yes, we can include financial analysis such as ratio analysis, break-even analysis, NPV/IRR calculations, cost-benefit analysis, and financial projections when relevant to the case.',
                        ],
                        [
                            'question' => 'What if my case study has specific questions to answer?',
                            'answer' => 'Perfect! Share all the case questions with us. We\'ll structure our analysis to specifically address each question with detailed, well-supported answers.',
                        ],
                        [
                            'question' => 'Can you help with group case presentations?',
                            'answer' => 'Absolutely! We can provide written analysis for your group and can also help create presentation slides with key findings, analysis, and recommendations for your group presentation.',
                        ],
                    ],
                    'deliverables' => [
                        'Complete case study analysis',
                        'Executive summary',
                        'SWOT analysis (and other frameworks)',
                        'Financial analysis (if applicable)',
                        'Strategic recommendations with justification',
                        'Implementation plan with timeline',
                        'Properly cited references',
                        'Presentation slides (optional add-on)',
                    ],
                    'guarantees' => [
                        'Industry expertise',
                        'Thorough analysis',
                        'Practical recommendations',
                        'Timely delivery',
                        'Business theory integration',
                        'Professional quality',
                    ],
                ],
            ],

            // Continue with remaining services (Literature Review, Presentation, Proofreading, Math)...
            // Due to length constraints, I'll include condensed versions

            // 7. LITERATURE REVIEW
            [
                'service' => [
                    'name' => 'Literature Review Help',
                    'slug' => 'literature-review',
                    'icon' => '📖',
                    'short_description' => 'Comprehensive literature review with source synthesis, critical analysis, and research gap identification.',
                    'long_description' => 'Expert literature review writing for research papers and dissertations. We synthesize multiple scholarly sources, identify research gaps, provide critical analysis, and create comprehensive reviews that demonstrate deep understanding of your field.',
                    'base_price_per_page' => 25.00,
                    'turnaround_min_hours' => 48,
                    'turnaround_max_hours' => 168,
                    'rating' => 4.9,
                    'orders_completed' => 2650,
                    'features' => ['Source synthesis', 'Critical analysis', 'Research gaps', 'Proper citations', 'Peer-reviewed sources', 'Thematic organization'],
                    'academic_levels' => ['University', 'Masters', 'PhD'],
                    'subjects' => ['All academic fields'],
                    'is_active' => true,
                    'display_order' => 7,
                    'meta_title' => 'Literature Review Help | Academic Research Writing from $25/page',
                    'meta_description' => 'Professional literature review writing with source synthesis and critical analysis. Peer-reviewed sources. Starting at $25/page.',
                ],
                'details' => [
                    'hero_title' => 'Professional Literature Review Writing',
                    'hero_subtitle' => 'Expert synthesis and critical analysis',
                    'hero_description' => 'Get comprehensive literature reviews that synthesize research, identify gaps, and provide critical analysis for your academic project.',
                    'what_we_offer' => [
                        'Source Identification',
                        'Critical Evaluation',
                        'Synthesis of Findings',
                        'Gap Analysis',
                        'Theoretical Framework',
                        'Proper Citations',
                    ],
                    'pricing_tiers' => [
                        ['name' => 'Standard', 'price' => '$25', 'timeframe' => 'per page', 'features' => ['7-14 days', '15+ sources', 'Critical analysis', 'Proper citations', 'Free revisions']],
                        ['name' => 'Advanced', 'price' => '$33', 'timeframe' => 'per page', 'features' => ['3-7 days', '25+ sources', 'Gap identification', 'Thematic synthesis', 'Multiple revisions']],
                        ['name' => 'PhD Level', 'price' => '$45', 'timeframe' => 'per page', 'features' => ['Express delivery', '40+ sources', 'Theoretical framework', 'Systematic review', 'Unlimited revisions']],
                    ],
                    'process_steps' => [
                        ['title' => 'Topic Refinement', 'description' => 'Define your research topic and scope for the literature review.'],
                        ['title' => 'Source Collection', 'description' => 'Gather relevant peer-reviewed sources from academic databases.'],
                        ['title' => 'Analysis & Synthesis', 'description' => 'Critically analyze sources and synthesize findings thematically.'],
                        ['title' => 'Writing & Formatting', 'description' => 'Write comprehensive review with proper citations and structure.'],
                    ],
                    'sample_topics' => [],
                    'testimonials' => [
                        ['name' => 'Dr. Sarah M.', 'level' => 'PhD Candidate', 'university' => 'Oxford', 'rating' => 5, 'review' => 'Exceptional literature review! Comprehensive synthesis of 50+ sources with excellent critical analysis.'],
                        ['name' => 'Mark R.', 'level' => 'Master\'s Student', 'university' => 'Cambridge', 'rating' => 5, 'review' => 'The gap analysis was spot-on and helped shape my entire research project. Highly recommend!'],
                        ['name' => 'Lisa T.', 'level' => 'Graduate Student', 'university' => 'Toronto', 'rating' => 5, 'review' => 'Professional quality work. The thematic organization made complex research easy to follow.'],
                    ],
                    'faqs' => [
                        ['question' => 'How many sources will be included?', 'answer' => 'Typically 15-25 for master\'s level and 30-50+ for PhD level. The exact number depends on your field and requirements.'],
                        ['question' => 'What is a systematic literature review?', 'answer' => 'A systematic review follows a structured methodology to identify, select, and critically appraise research. We can conduct systematic reviews following PRISMA or other guidelines.'],
                        ['question' => 'Can you identify research gaps?', 'answer' => 'Yes! Gap analysis is a key component. We identify what has been studied, what remains unknown, and where your research can contribute.'],
                        ['question' => 'Do you use only peer-reviewed sources?', 'answer' => 'Yes, we primarily use peer-reviewed journal articles, academic books, and credible scholarly sources from databases like JSTOR, PubMed, IEEE, etc.'],
                    ],
                    'citation_styles' => ['APA', 'MLA', 'Chicago', 'Harvard'],
                    'deliverables' => [
                        'Complete literature review',
                        'Synthesized research findings',
                        'Critical analysis',
                        'Annotated bibliography',
                        'Properly cited sources',
                        'Gap analysis',
                    ],
                    'guarantees' => [
                        'Quality peer-reviewed sources',
                        'Critical analysis',
                        'Academic standards',
                        'Plagiarism-free',
                        'Expert researchers',
                        'Revision support',
                    ],
                ],
            ],

            // 8. PRESENTATION DESIGN
            [
                'service' => [
                    'name' => 'Presentation Design',
                    'slug' => 'presentation-design',
                    'icon' => '📊',
                    'short_description' => 'Professional PowerPoint and presentation creation with visual design and engaging content.',
                    'long_description' => 'Create stunning presentations for academic or business needs. We design visually appealing slides with clear content, professional layouts, charts, graphics, and speaker notes.',
                    'base_price_per_page' => 10.00,
                    'turnaround_min_hours' => 12,
                    'turnaround_max_hours' => 48,
                    'rating' => 4.7,
                    'orders_completed' => 4280,
                    'features' => ['Visual design', 'Clear content', 'Speaker notes', 'Multiple formats', 'Charts & graphics', 'Professional layouts'],
                    'academic_levels' => ['High School', 'College', 'University', 'Masters', 'PhD'],
                    'subjects' => ['All subjects'],
                    'is_active' => true,
                    'display_order' => 8,
                    'meta_title' => 'Presentation Design Service | PowerPoint Help from $10/slide',
                    'meta_description' => 'Professional presentation design with visual appeal and clear content. PowerPoint, Keynote, Google Slides. $10/slide.',
                ],
                'details' => [
                    'hero_title' => 'Professional Presentation Design',
                    'hero_subtitle' => 'Visually stunning slides that engage your audience',
                    'hero_description' => 'Get professionally designed presentations with clear content, visual appeal, and engaging layouts for any subject.',
                    'what_we_offer' => [
                        'PowerPoint Design',
                        'Keynote Presentations',
                        'Google Slides',
                        'Visual Elements & Graphics',
                        'Charts & Graphs',
                        'Speaker Notes',
                        'Custom Templates',
                        'Animation Effects',
                    ],
                    'pricing_tiers' => [
                        ['name' => 'Basic', 'price' => '$10', 'timeframe' => 'per slide', 'features' => ['Professional design', 'Text content', 'Basic graphics', '48-hour delivery']],
                        ['name' => 'Premium', 'price' => '$15', 'timeframe' => 'per slide', 'features' => ['Custom design', 'Advanced graphics', 'Charts & diagrams', 'Speaker notes', '24-hour delivery']],
                        ['name' => 'Executive', 'price' => '$25', 'timeframe' => 'per slide', 'features' => ['Luxury design', 'Custom illustrations', 'Animations', 'Full speaker script', '12-hour delivery']],
                    ],
                    'process_steps' => [
                        ['title' => 'Share Content', 'description' => 'Provide your presentation topic, key points, and any required content or materials.'],
                        ['title' => 'Design Creation', 'description' => 'Our designers create visually appealing slides with your content professionally laid out.'],
                        ['title' => 'Review & Refine', 'description' => 'Review the presentation and request any changes or refinements needed.'],
                        ['title' => 'Final Delivery', 'description' => 'Receive editable presentation file with speaker notes and any supporting materials.'],
                    ],
                    'sample_topics' => [],
                    'testimonials' => [
                        ['name' => 'John D.', 'level' => 'MBA Student', 'university' => 'Stanford', 'rating' => 5, 'review' => 'Amazing presentation design! The slides were professional and the charts were clear. Nailed my pitch!'],
                        ['name' => 'Rachel K.', 'level' => 'College Senior', 'university' => 'Duke', 'rating' => 5, 'review' => 'Perfect for my capstone presentation. The design was engaging and the speaker notes were helpful.'],
                        ['name' => 'Mike T.', 'level' => 'Graduate Student', 'university' => 'Cornell', 'rating' => 5, 'review' => 'Excellent work on my thesis defense slides. Professional, clear, and visually appealing.'],
                    ],
                    'faqs' => [
                        ['question' => 'What formats do you support?', 'answer' => 'We create presentations in PowerPoint (.pptx), Keynote, Google Slides, and PDF formats. All files are fully editable.'],
                        ['question' => 'Can you add animations and transitions?', 'answer' => 'Yes! We can add professional animations, transitions, and multimedia elements to make your presentation more engaging.'],
                        ['question' => 'Do you write the content or just design?', 'answer' => 'We offer both! We can design slides with your content or create both the content and design from your topic and key points.'],
                        ['question' => 'Can you match my company/university branding?', 'answer' => 'Absolutely! Share your brand guidelines, colors, logos, and fonts, and we\'ll create presentations that match your brand identity.'],
                    ],
                    'deliverables' => [
                        'Complete presentation file',
                        'Editable source file',
                        'Speaker notes for each slide',
                        'Charts and graphics',
                        'References slide',
                        'PDF version',
                    ],
                    'guarantees' => [
                        'Professional design',
                        'Clear content',
                        'Multiple revisions',
                        'Fast turnaround',
                        'Editable files',
                        'Satisfaction guaranteed',
                    ],
                ],
            ],

            // 9. PROOFREADING & EDITING
            [
                'service' => [
                    'name' => 'Proofreading & Editing',
                    'slug' => 'proofreading-editing',
                    'icon' => '✍️',
                    'short_description' => 'Professional editing and proofreading to improve grammar, clarity, style, and formatting.',
                    'long_description' => 'Expert proofreading and editing for all academic documents. We correct grammar, improve clarity, enhance style, ensure proper formatting, and check citations for consistency and accuracy.',
                    'base_price_per_page' => 8.00,
                    'turnaround_min_hours' => 6,
                    'turnaround_max_hours' => 24,
                    'rating' => 4.9,
                    'orders_completed' => 6740,
                    'features' => ['Grammar correction', 'Style improvement', 'Citation check', 'Fast turnaround', 'Track changes', 'Comments & suggestions'],
                    'academic_levels' => ['High School', 'College', 'University', 'Masters', 'PhD'],
                    'subjects' => ['All documents'],
                    'is_active' => true,
                    'display_order' => 9,
                    'meta_title' => 'Proofreading & Editing Service | Academic Papers from $8/page',
                    'meta_description' => 'Professional proofreading and editing for academic papers. Grammar, style, citations checked. From $8/page.',
                ],
                'details' => [
                    'hero_title' => 'Professional Proofreading & Editing',
                    'hero_subtitle' => 'Polish your work to perfection',
                    'hero_description' => 'Get expert proofreading and editing to improve grammar, clarity, style, and formatting of your academic work.',
                    'what_we_offer' => [
                        'Grammar & Spelling Correction',
                        'Punctuation & Syntax',
                        'Sentence Structure Enhancement',
                        'Clarity & Readability',
                        'Style & Tone Consistency',
                        'Citation Formatting',
                        'Consistency Checks',
                        'Formatting Review',
                    ],
                    'pricing_tiers' => [
                        ['name' => 'Proofreading', 'price' => '$8', 'timeframe' => 'per page', 'features' => ['Grammar & spelling', 'Punctuation', 'Basic formatting', '24-hour delivery']],
                        ['name' => 'Copy Editing', 'price' => '$12', 'timeframe' => 'per page', 'features' => ['Everything in Proofreading', 'Style improvement', 'Citation check', 'Clarity enhancement', '12-hour delivery']],
                        ['name' => 'Substantive Editing', 'price' => '$18', 'timeframe' => 'per page', 'features' => ['Everything in Copy Editing', 'Structure review', 'Argument strengthening', 'Comprehensive feedback', '6-hour option']],
                    ],
                    'process_steps' => [
                        ['title' => 'Submit Document', 'description' => 'Upload your document and specify the level of editing needed and any specific concerns.'],
                        ['title' => 'Expert Review', 'description' => 'A professional editor reviews your work using track changes to show all corrections.'],
                        ['title' => 'Editing Complete', 'description' => 'Receive edited document with track changes, comments, and a summary of improvements made.'],
                        ['title' => 'Revision Support', 'description' => 'Review changes and ask questions. Request clarification on any edits as needed.'],
                    ],
                    'sample_topics' => [],
                    'testimonials' => [
                        ['name' => 'Emma W.', 'level' => 'PhD Candidate', 'university' => 'Princeton', 'rating' => 5, 'review' => 'Meticulous editing! Caught errors I missed and improved clarity throughout. My paper is so much stronger now.'],
                        ['name' => 'Carlos R.', 'level' => 'International Student', 'university' => 'UCLA', 'rating' => 5, 'review' => 'As a non-native English speaker, this service is invaluable. My writing is now polished and professional.'],
                        ['name' => 'Sophie L.', 'level' => 'Master\'s Student', 'university' => 'Yale', 'rating' => 5, 'review' => 'Fast and thorough! The editor improved my thesis clarity and fixed all citation inconsistencies. Perfect!'],
                    ],
                    'faqs' => [
                        ['question' => 'What\'s the difference between proofreading and editing?', 'answer' => 'Proofreading corrects grammar, spelling, and punctuation. Copy editing also improves style, clarity, and flow. Substantive editing additionally reviews structure, arguments, and provides comprehensive feedback.'],
                        ['question' => 'Will you rewrite my paper?', 'answer' => 'No, we edit and improve your existing work. We maintain your voice and ideas while enhancing clarity, grammar, and style. For rewriting needs, consider our writing services.'],
                        ['question' => 'Do you use track changes?', 'answer' => 'Yes! We use Microsoft Word track changes so you can see every correction and comment we make. This helps you learn from the edits and decide which changes to accept.'],
                        ['question' => 'Can you check my citations and references?', 'answer' => 'Absolutely! We check citation format consistency, ensure all in-text citations have corresponding references, and verify formatting meets your required style guide (APA, MLA, etc.).'],
                    ],
                    'deliverables' => [
                        'Edited document with track changes',
                        'Clean version without markups',
                        'Summary of changes made',
                        'Grammar and spelling corrections',
                        'Style and clarity improvements',
                        'Citation formatting review',
                        'Editor comments and suggestions',
                    ],
                    'guarantees' => [
                        'Professional editors',
                        'Thorough review',
                        'Quick turnaround',
                        'Multiple revision rounds',
                        'Confidentiality protected',
                        'Satisfaction guaranteed',
                    ],
                ],
            ],

            // 10. MATH PROBLEM SOLVING
            [
                'service' => [
                    'name' => 'Math Problem Solving',
                    'slug' => 'math-problem-solving',
                    'icon' => '🧮',
                    'short_description' => 'Expert mathematics help with step-by-step solutions from algebra to advanced calculus.',
                    'long_description' => 'Get help with math problems from algebra to calculus and beyond. Our math experts provide detailed step-by-step solutions with clear explanations, graphs, and visual aids for better understanding.',
                    'base_price_per_page' => 10.00,
                    'turnaround_min_hours' => 3,
                    'turnaround_max_hours' => 24,
                    'rating' => 4.8,
                    'orders_completed' => 7850,
                    'features' => ['All math levels', 'Step-by-step solutions', 'Visual aids & graphs', 'Quick turnaround', 'Clear explanations', 'Formula sheets'],
                    'academic_levels' => ['High School', 'College', 'University'],
                    'subjects' => ['Algebra', 'Calculus', 'Statistics', 'Linear Algebra', 'Discrete Math', 'Trigonometry', 'Geometry', 'Probability'],
                    'is_active' => true,
                    'display_order' => 10,
                    'meta_title' => 'Math Problem Solving Help | All Math Levels from $10/page',
                    'meta_description' => 'Expert math homework help with step-by-step solutions. Algebra, calculus, statistics, and more. From $10/problem.',
                ],
                'details' => [
                    'hero_title' => 'Expert Math Problem Solving',
                    'hero_subtitle' => 'Step-by-step solutions for all math levels',
                    'hero_description' => 'Get detailed solutions to your math problems with clear explanations, graphs, and visual aids from experienced math tutors.',
                    'what_we_offer' => [
                        'Algebra - Equations, inequalities, polynomials',
                        'Calculus - Differential & Integral calculus',
                        'Statistics - Probability & statistical analysis',
                        'Linear Algebra - Matrices, vectors, transformations',
                        'Discrete Mathematics - Logic, sets, combinatorics',
                        'Trigonometry - Angles, functions, identities',
                        'Geometry - Shapes, proofs, theorems',
                        'Differential Equations - ODEs and PDEs',
                    ],
                    'pricing_tiers' => [
                        ['name' => 'Standard', 'price' => '$10', 'timeframe' => 'per page', 'features' => ['12-24 hours', 'Step-by-step', 'Work shown', 'Basic graphs']],
                        ['name' => 'Express', 'price' => '$15', 'timeframe' => 'per page', 'features' => ['6-12 hours', 'Detailed explanations', 'Multiple methods', 'Professional graphs']],
                        ['name' => 'Urgent', 'price' => '$20', 'timeframe' => 'per page', 'features' => ['3-6 hours', 'Priority service', 'Extra explanations', 'Video walkthrough option']],
                    ],
                    'process_steps' => [
                        ['title' => 'Submit Problems', 'description' => 'Share your math problems with any instructions, formulas, or context provided by your instructor.'],
                        ['title' => 'Expert Solution', 'description' => 'A math expert solves each problem showing all steps, calculations, and reasoning.'],
                        ['title' => 'Review & Learn', 'description' => 'Receive solutions with explanations and graphs. Review to understand the methods used.'],
                        ['title' => 'Ask Questions', 'description' => 'Don\'t understand a step? Ask follow-up questions for additional clarification.'],
                    ],
                    'sample_topics' => [],
                    'testimonials' => [
                        ['name' => 'Jake M.', 'level' => 'High School Junior', 'university' => 'Madison HS', 'rating' => 5, 'review' => 'Finally understand calculus! The step-by-step solutions showed me exactly where I was going wrong. Math tutor is amazing!'],
                        ['name' => 'Priya S.', 'level' => 'College Sophomore', 'university' => 'Georgia Tech', 'rating' => 5, 'review' => 'Perfect for my linear algebra homework. Every matrix operation was shown clearly with explanations. Got 100%!'],
                        ['name' => 'Tyler K.', 'level' => 'University Student', 'university' => 'Penn State', 'rating' => 5, 'review' => 'Statistics homework was impossible until I found this service. Clear explanations and correct solutions every time.'],
                    ],
                    'faqs' => [
                        ['question' => 'What math topics do you cover?', 'answer' => 'We cover all high school and college math including Algebra, Geometry, Trigonometry, Pre-Calculus, Calculus I-III, Statistics, Linear Algebra, Discrete Math, Differential Equations, and more.'],
                        ['question' => 'Do you show all the steps?', 'answer' => 'Yes! Every solution includes detailed step-by-step work showing how we arrived at the answer. This helps you understand the process and learn the methods.'],
                        ['question' => 'Can you create graphs and diagrams?', 'answer' => 'Absolutely! We provide graphs for functions, geometric diagrams, statistical plots, and any visual aids needed to understand the problem and solution.'],
                        ['question' => 'What if I need help understanding a solution?', 'answer' => 'Just ask! We welcome follow-up questions. If any step or concept isn\'t clear, we\'ll provide additional explanation until you fully understand.'],
                    ],
                    'deliverables' => [
                        'Step-by-step solutions',
                        'All work shown',
                        'Graphs and diagrams',
                        'Clear explanations',
                        'Formula reference sheets',
                        'Final answers highlighted',
                    ],
                    'guarantees' => [
                        'Accurate solutions',
                        'Clear step-by-step work',
                        'Quick turnaround',
                        'Expert math tutors',
                        'Follow-up support',
                        'Money-back if incorrect',
                    ],
                ],
            ],
        ];
    }
}
